---
apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: myhybrid-200215
  name: dagit
spec:
  description: DAGS
  format: DOCKER
  location: us-central1
  resourceID: dagit
